namespace FLRecordsData {
    export interface LabelValueOption {
        value: string;
        label: string;
    }

    export interface SectionDef {
        key: string;
        label: string;
    }

    export interface PresetOptions {
        genre: string[];
        feel: string[];
        tone: string[];
        arrangement: string[];
        instrumentation: string[];
        groove: string[];
        band: string[];
        leadvocal: string[];
        backingvocal: string[];
        language: string[];
        key: string[];
        timesig: string[];
        bpmMode: LabelValueOption[];
    }

    export var hybridPresetFields: string[] = [
        "genre",
        "feel",
        "tone",
        "arrangement",
        "instrumentation",
        "groove",
        "band",
        "leadvocal",
        "backingvocal"
    ];

    export var sectionDefs: SectionDef[] = [
        { key: "intro", label: "Intro" },
        { key: "verse1", label: "Verse 1" },
        { key: "chorus", label: "Chorus" },
        { key: "verse2", label: "Verse 2" },
        { key: "bridge", label: "Bridge" },
        { key: "outro", label: "Outro" }
    ];

    export var presetOptions: PresetOptions = {
        genre: [
            "Futurepop / Synthpop",
            "Electropop",
            "Synth-Funk",
            "Synthwave",
            "Darksynth",
            "Retrowave",
            "Vaporwave",
            "Chillwave",
            "Hyperpop",
            "House / Disco Hybrid",
            "Deep House",
            "Tech House",
            "Progressive House",
            "Afro House",
            "Acid House",
            "Chicago House",
            "French Touch",
            "Nu-Disco",
            "Italo Disco",
            "Eurodance",
            "Techno",
            "Detroit Electro",
            "Minimal Techno",
            "Dub Techno",
            "EBM (Electronic Body Music)",
            "Ambient Techno",
            "Breakbeat",
            "Big Beat",
            "Jungle",
            "Drum & Bass",
            "Liquid Drum & Bass",
            "Darkstep / Neurofunk",
            "Dubstep",
            "Future Bass",
            "UK Garage",
            "Grime",
            "Jersey Club",
            "2-Step Garage",
            "Bassline / Speed Garage",
            "Trip-Hop",
            "Downtempo",
            "Lo-Fi Beats",
            "Ambient",
            "New Age / Space Music",
            "Balearic / Sunset Chill",
            "Trance",
            "Psytrance",
            "Progressive Trance",
            "Vocal Trance",
            "Boom-Bap Hip-Hop",
            "Trap",
            "Cloud Rap",
            "Phonk",
            "Neo-Soul",
            "Contemporary R&B",
            "Electrofunk",
            "Funk",
            "Boogie",
            "G-Funk",
            "Post-Punk",
            "Gothic Rock",
            "Shoegaze",
            "Dream Pop",
            "Noise Pop",
            "Indie Rock",
            "Garage Rock",
            "Surf Rock",
            "Psychedelic Rock",
            "Stoner Rock / Desert Rock",
            "Grunge",
            "Pop Punk",
            "Hardcore Punk",
            "Skate Punk / Melodic Punk",
            "Emo / Post-Emo",
            "Screamo / Skramz",
            "Punkfuture",
            "Metal Future",
            "Industrial Metal",
            "Industrial Pop",
            "Thrash Metal",
            "Progressive Metal",
            "Djent",
            "Doom Metal",
            "Black Metal",
            "Metalcore / Post-Hardcore",
            "Math Rock",
            "Post-Rock",
            "Post-Metal",
            "Neue Deutsche Harte",
            "Darkwave",
            "Coldwave",
            "Witch House",
            "Dark Ambient",
            "Aggrotech",
            "Industrial Electro",
            "Deathrock",
            "Dance-Pop",
            "Bubblegum Pop",
            "Art Pop",
            "Experimental Pop",
            "Chamber Pop",
            "Baroque Pop",
            "K-Pop Futurism",
            "City Pop",
            "J-Pop / Shibuya-kei",
            "Twee Pop",
            "Jazz Fusion",
            "Acid Jazz",
            "Nu Jazz / Jazztronica",
            "Smooth Jazz",
            "Bebop",
            "Free Jazz / Avant-Garde Jazz",
            "Jazz Rap",
            "Ska",
            "Ska Punk",
            "Reggae",
            "Dub",
            "Dancehall",
            "Lovers Rock",
            "Reggaeton",
            "Latin House",
            "Cumbia Digital",
            "Bossa Nova",
            "Tropicalia",
            "Afrobeat",
            "Amapiano",
            "Kuduro",
            "Dembow",
            "Soca",
            "Calypso",
            "Celtic / Folk-Electronic",
            "Balkan Beat",
            "Bollywood Fusion",
            "Middle Eastern Electronic",
            "Tuareg Desert Blues",
            "Highlife",
            "Soukous",
            "Fado (modernized)",
            "Flamenco Fusion",
            "Klezmer Punk",
            "Outlaw Country",
            "Alt-Country / Americana",
            "Country Pop",
            "Cosmic Country",
            "Western Swing",
            "Electric Blues",
            "Delta Blues (modernized)",
            "Northern Soul",
            "Classic Soul",
            "Gospel",
            "Motown",
            "Neoclassical",
            "Orchestral Cinematic",
            "Classical Crossover",
            "Minimal / Post-Minimal",
            "Glitch",
            "IDM (Intelligent Dance Music)",
            "Noise",
            "Drone",
            "Musique Concrete",
            "Plunderphonics",
            "Hauntology / Ghost Box",
            "Chiptune",
            "Bitpop",
            "Video Game Soundtrack",
            "Nintendocore",
            "Footwork / Juke",
            "Hardstyle",
            "Gabber / Hardcore",
            "Happy Hardcore",
            "Speedcore",
            "Breakcore",
            "Folktronica",
            "Indietronica",
            "Electro Swing",
            "Steampunk Cabaret"
        ],
        feel: [
            "euphoric and driving",
            "warm and intimate",
            "swaggering and playful",
            "melancholy but resilient",
            "hypnotic and nocturnal",
            "tense and cinematic",
            "romantic and weightless",
            "aggressive and kinetic",
            "loose and human",
            "glossy and triumphant",
            "dreamy and dissociative",
            "brooding and stormy",
            "hopeful and wide-open",
            "shuffling and body-moving",
            "anxious and jittery",
            "bittersweet and reflective",
            "carefree and sun-drenched",
            "defiant and anthemic",
            "eerie and unsettling",
            "fierce and empowering",
            "haunted and longing",
            "irreverent and chaotic",
            "lazy and drifting",
            "majestic and soaring",
            "paranoid and claustrophobic",
            "peaceful and meditative",
            "raw and confessional",
            "sarcastic and detached",
            "sensual and slow-burning",
            "spiritual and transcendent",
            "vengeful and sharp-edged",
            "wistful and fading",
            "frantic and overwhelming",
            "celebratory and larger-than-life",
            "mysterious and fog-wrapped",
            "goofy and irreverent"
        ],
        tone: [
            "neon-lit and glossy",
            "gritty and raw",
            "organic and lived-in",
            "chrome-plated and futuristic",
            "dusty and tape-worn",
            "dark and haunted",
            "sun-bleached and nostalgic",
            "expensive and cinematic",
            "intimate and close-mic",
            "cold and mechanical",
            "lush and romantic",
            "playful and hyper-saturated",
            "cavernous and reverb-drenched",
            "crisp and hi-fi digital",
            "lo-fi and cassette-warm",
            "underwater and submerged",
            "smoggy and distortion-heavy",
            "crystalline and shimmering",
            "weathered and analog-decayed",
            "punchy and in-your-face",
            "spacious and wide-screen",
            "claustrophobic and compressed",
            "pastoral and open-air",
            "sepia-toned and vintage",
            "holographic and prismatic",
            "scorched and overdriven",
            "gossamer and barely-there",
            "monochrome and stark",
            "thick and syrupy",
            "brittle and fractured"
        ],
        arrangement: [
            "hook-first verse / chorus with a breakdown and final lift",
            "slow-burn intro into a hard chorus lift",
            "DJ-friendly extended mix with long transitions",
            "verse / pre-chorus / chorus / bridge pop structure",
            "chant-driven loop that grows in layers",
            "minimal opening that blooms into a maximal finish",
            "instrumental showcase between choruses",
            "call-and-response vocal arrangement",
            "cinematic rise with a final payoff chorus",
            "club tool structure with frequent drops and builds",
            "AABA classic song form with modern production",
            "through-composed narrative with no repeated sections",
            "verse / chorus / verse / chorus / double chorus out",
            "intro jam that locks a groove then adds vocals mid-song",
            "spoken-word intro into a beat-drop payoff",
            "strophic folk form with evolving instrumentation each verse",
            "medley / suite with distinct movements stitched together",
            "stripped acoustic open into full-band explosion",
            "tension-release cycles with no traditional chorus",
            "round-robin vocal sections trading lead between voices",
            "ambient first half into driving second half",
            "false ending followed by a surprise final section",
            "refrain-heavy anthem structure with singalong repetition",
            "duet structure alternating perspectives each verse"
        ],
        instrumentation: [
            "analog synth stack, live bass, and tight drum programming",
            "electric piano, dry drum kit, and rubbery bass",
            "FM synths, drum machines, and bright octave leads",
            "guitars, live drums, bass, and layered vocal doubles",
            "modular synth textures, sub bass, and restrained percussion",
            "horn section, clavinet, rhythm guitar, and live drums",
            "string pads, piano, arpeggiators, and gated drums",
            "breakbeat chops, samplers, bass guitar, and effect throws",
            "distorted guitars, synth bass, and machine percussion",
            "ska upstrokes, live brass, bass pocket, and snare-forward drums",
            "chiptune leads, crunchy drums, and wide supporting pads",
            "sitar, tabla, synth drones, and electronic percussion",
            "steel drums, congas, marimba, and slap bass",
            "pipe organ, choir pads, orchestral hits, and booming timpani",
            "turntable scratches, sampled horns, MPC drums, and 808 bass",
            "acoustic guitar, upright bass, brushed drums, and pedal steel",
            "theremin, tape loops, analog delay, and bowed vibraphone",
            "west-African kora, djembe, kalimba, and synth bass",
            "harpsichord, chamber strings, celeste, and programmed beats",
            "sax solo breaks, Rhodes keys, fingerstyle bass, and brushed snare",
            "prepared piano, granular textures, and field recordings",
            "banjo, fiddle, harmonica, and stomping percussion",
            "talkbox, wah guitar, slap bass, and tight hi-hats",
            "accordion, nylon guitar, hand claps, and shaker groove",
            "dual guitar attack, double kick drums, and growling bass",
            "harp, flute, glockenspiel, and soft mallet percussion",
            "massive detuned saw leads, sidechained pads, and sub-rattling 808s",
            "lap steel, wurlitzer, room-mic drums, and vintage spring reverb"
        ],
        groove: [
            "four-on-the-floor pulse with syncopated percussion",
            "laid-back pocket just behind the beat",
            "tight disco strut with open-hat lift",
            "swung breakbeat with ghost-note movement",
            "motorik pulse that never lets up",
            "half-time head-nod with low-end drag",
            "rolling jungle momentum",
            "ska upstroke bounce",
            "shuffling pocket with human push-pull",
            "locked electro snap",
            "dubwise lurch and spacious echoes",
            "New Orleans second-line swing",
            "bossa nova sway with brushed cross-stick",
            "trap hi-hat rolls with 808 bounce",
            "go-go swing with conga-driven push",
            "reggaeton dembow riddim",
            "footwork juke stutter at 160 BPM",
            "afrobeat polyrhythmic interlock",
            "waltz-time sway with electronic undercurrent",
            "soca party drive with rapid snare accents",
            "blast beat fury with double-kick barrage",
            "krautrock metronomic precision",
            "boom-bap boom-clap with vinyl crackle",
            "cumbia chugging offbeat",
            "swing-era big-band bounce",
            "glitchy stuttered micro-edits",
            "marching cadence with militaristic snare rolls",
            "surf-rock spring-reverb tom gallop"
        ],
        band: [
            "hybrid electronic band with expressive lead vocal",
            "tight five-piece live session band",
            "machine-precise producer duo and featured vocalist",
            "loose late-night bar band with real human imperfection",
            "virtuoso trio with rhythm-section chemistry",
            "club producer with hype vocal chops and stacked harmonies",
            "punk rhythm section with synth operator support",
            "dubwise studio crew with live overdubs",
            "orchestral-electronic ensemble with cinematic players",
            "solo bedroom producer with laptop and MIDI controller",
            "supergroup of session legends trading solos",
            "DJ and MC tandem with live turntablism",
            "string quartet augmented by subtle electronics",
            "big band horn section with rhythm combo",
            "all-vocal a cappella group with beatboxer",
            "power duo of guitar and drums only",
            "lo-fi four-track home-recording project",
            "Afrobeat-style large ensemble with multiple percussionists",
            "singer-songwriter with sparse piano accompaniment",
            "marching band reimagined with electronic backline"
        ],
        leadvocal: [
            "breathy femme lead",
            "soulful tenor lead",
            "androgynous synthpop lead",
            "gritty baritone lead",
            "sweet high-register pop lead",
            "detached coldwave lead",
            "animated punk lead",
            "silky neo-soul lead",
            "robotic vocoder lead",
            "spoken-word / half-sung lead",
            "theatrical glam lead",
            "rap-sung crossover lead",
            "deep bass / basso profondo lead",
            "raspy blues-rock belter",
            "airy falsetto lead",
            "operatic soprano lead",
            "gravel-voiced Tom Waits-style storyteller",
            "Auto-Tuned melodic rap lead",
            "whispery ASMR-close lead",
            "shouting hardcore lead",
            "crooning lounge-jazz lead",
            "nasal indie-folk lead",
            "chanting / mantra-style lead",
            "dual-voice harmony lead (two singers as one)",
            "growled / screamed metal lead",
            "yodel-inflected lead",
            "conversational talk-singing lead",
            "child-like innocent vocal lead"
        ],
        backingvocal: [
            "no background singers",
            "tight unison doubles",
            "airy female harmonies",
            "stacked mixed-gender chorus",
            "call-and-response hype voices",
            "gospel-style backing stack",
            "robotic vocoder choir",
            "whispered doubles and ghost harmonies",
            "punk gang vocals",
            "lush R&B harmony stack",
            "distant choir pad vocals",
            "octave doubles only",
            "barbershop-style close harmonies",
            "chanted crowd vocals",
            "ethereal wordless soprano ooh-ahhs",
            "doo-wop vocal group style",
            "throat-singing overtone textures",
            "children's choir accents",
            "sampled and pitched vocal chops",
            "layered self-harmony (one voice stacked many times)",
            "spoken-word ensemble recitation",
            "antiphonal split-stereo call and answer"
        ],
        language: [
            "English",
            "Instrumental / non-vocal",
            "Bilingual / code-switching",
            "English with Japanese hooks",
            "English with Korean hooks",
            "Spanish",
            "Japanese",
            "Korean",
            "French",
            "Portuguese",
            "German",
            "Italian",
            "Mandarin Chinese",
            "Cantonese",
            "Hindi",
            "Arabic",
            "Swahili",
            "Russian",
            "Swedish",
            "Icelandic",
            "Yoruba",
            "Tagalog / Filipino",
            "Hawaiian / Pidgin",
            "Turkish",
            "Hebrew",
            "Creole / Patois",
            "Constructed language / conlang",
            "Scat / vocables / nonsense syllables"
        ],
        key: [
            "C major",
            "C minor",
            "C Dorian",
            "C Mixolydian",
            "Db major",
            "Db minor",
            "D major",
            "D minor",
            "D Dorian",
            "Eb major",
            "Eb minor",
            "E major",
            "E minor",
            "E Phrygian",
            "F major",
            "F minor",
            "F Lydian",
            "F# major",
            "F# minor",
            "G major",
            "G minor",
            "G Mixolydian",
            "Ab major",
            "Ab minor",
            "A major",
            "A minor",
            "A Dorian",
            "A harmonic minor",
            "Bb major",
            "Bb minor",
            "B major",
            "B minor",
            "B Locrian",
            "C blues scale",
            "A blues scale",
            "E blues scale",
            "D Phrygian dominant (Spanish)",
            "A Hungarian minor",
            "Whole-tone scale",
            "Chromatic / atonal"
        ],
        timesig: [
            "4/4",
            "3/4",
            "6/8",
            "12/8",
            "5/4",
            "7/8",
            "2/4",
            "6/4",
            "9/8",
            "11/8",
            "7/4",
            "5/8",
            "mixed meter / shifting"
        ],
        bpmMode: [
            { value: "genre_default", label: "Match genre default" },
            { value: "slow_genre", label: "Slow for genre" },
            { value: "mid_genre", label: "Midtempo for genre" },
            { value: "fast_genre", label: "Fast for genre" },
            { value: "half_time", label: "Half-time feel" },
            { value: "double_time", label: "Double-time feel" },
            { value: "rubato", label: "Rubato / free tempo" },
            { value: "accelerando", label: "Gradual accelerando" },
            { value: "custom_numeric", label: "Custom numeric" }
        ]
    };
}
